---
- hosts: all
  become: true

  tasks:
    - # this is exciting #
    - name: print all the ansible gathered facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == "Debian"